language: python
notifications:
  email: false
python:
  - "3.4"

# command to install dependencies
install:
  - pip3 install -r .travis.requirements.txt
#  - pip3 install flask
#  - pip3 install flask-restful
#  - pip3 install flask-sqlalchemy
#  - pip3 install flask-httpauth
#  - pip3 install tox
  
# command to run tests
script: tox