language: python

# command to enable and disable notifications
notifications:
  email: false

# command to set the python version
python:
  - "3.4"
  
# command to use mariadb
services:
  - mariadb: '10.0'  
  
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  
# command to run python scripts and tests
script:
  - runtests.sh