language: python

# command to enable and disable notifications
notifications:
  email: false

# command to set the python version
python:
  - "2.7"
  
# command to use mariadb
services:
  - postgresql
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run python scripts and tests
script:
  - runtests.sh