language: python

# command to enable and disable notifications
notifications:
  email: false

# command to set the python version
python:
  - "3.4"
  
# command to use mariadb
services:
  - mariadb: '10.0'  
  
# command to install dependencies
install:
  - pip3 install -r .travis.requirements.txt
  - pip install pytest-cov
  
before_script:
  - mysql -u root -e 'CREATE DATABASE swarm_intelligence'
  - mysqladmin -u root status
  - ping -c 3 localhost

# command to run python scripts and tests
script:
  - tox
  - py.test --cov-config .coveragerc --cov=swarm_intelligence_app swarm_intelligence_app/resources/tests/*